package io.github.vdaburon.jmeter.har.hartransactionmarker;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.vdaburon.jmeter.har.Utils;
import io.github.vdaburon.jmeter.har.common.TransactionInfo;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.security.InvalidParameterException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import static io.github.vdaburon.jmeter.har.Utils.timestampToIsoFormat;

/**
 * Parse a JSON file generated by the Har Transaction Marker a Chrome Plugin
 */
public class ManageExternalJson {
    public static final String K_NAME = "name";
    public static final String K_TYPE = "type";
    public static final String K_TYPE_START = "start";
    public static final String K_TYPE_END = "end";
    public static final String K_TIMESTAMP = "timestamp";

    private static final Logger LOGGER = Logger.getLogger(ManageExternalJson.class.getName());

    /**
     * Read the json file with transaction infos
     * @param fileName the json file to read and parse
     * @return a list of TransactionInfo
     */
    public static List<TransactionInfo> createListTransactionInfo(String fileName) {
        LOGGER.info("Read external file: " + fileName);
        if (fileName == null) {
            throw new InvalidParameterException("fileName must be not null");
        }

        /*
        [
          {
            "delivered": "timestamp-only",
            "id": "be74758b-6bb9-4b05-8d4a-494a6b50bc5b",
            "name": "welcome",
            "sequence": 1,
            "tabId": 863732429,
            "tabUrl": "https://springboot-jpetstore.apps.ocp4.innershift.sodigital.io/",
            "timestamp": 1771835412876,
            "type": "start",
            "windowId": 863732392
          },
          {
            "delivered": "timestamp-only",
            "id": "b0fbd709-6a7b-40a6-a07a-f8fa45982b6f",
            "name": "welcome",
            "sequence": 2,
            "tabId": 863732429,
            "tabUrl": "https://springboot-jpetstore.apps.ocp4.innershift.sodigital.io/",
            "timestamp": 1771835429492,
            "type": "end",
            "windowId": 863732392
          },
         */
        ArrayList<TransactionInfo> listTransactionInfo = new ArrayList();
        try {
            String json = Utils.readTextFile(fileName, StandardCharsets.UTF_8);

            ObjectMapper mapper = new ObjectMapper();
            // read the json String and convert it into JsonNode
            JsonNode arrayNode = mapper.readTree(json);
            if (arrayNode.isArray()) {
                for (JsonNode node : arrayNode) {
                    String sType = node.get(K_TYPE).asText();
                    if (K_TYPE_START.equalsIgnoreCase(sType)) {
                        TransactionInfo transactionInfo = new TransactionInfo();
                        transactionInfo.setName(node.get(K_NAME).asText());
                        String sDateTmp = timestampToIsoFormat(node.get(K_TIMESTAMP).asLong());
                        transactionInfo.setBeginDateTime(sDateTmp);
                        listTransactionInfo.add(transactionInfo);
                    }

                    if (K_TYPE_END.equalsIgnoreCase(sType)) {
                        String sDateTmp = timestampToIsoFormat(node.get(K_TIMESTAMP).asLong());
                        String name = node.get(K_NAME).asText();
                        int i = listTransactionInfo.size();
                        boolean isNotFind = true;
                        while (i > 0 && isNotFind) {
                            // find the transactionInfo by the name, reverse order
                            TransactionInfo transactionInfoTmp = listTransactionInfo.get(i - 1);
                            if (name.equals(transactionInfoTmp.getName())) {
                                isNotFind = false;
                                transactionInfoTmp.setEndDateTime(sDateTmp);
                            }
                            i--;
                        }
                    }
                }
            }

        } catch (IOException e) {
            LOGGER.warning("Warning when read file=" + fileName + "exception="+ e.toString());
        }
        LOGGER.info("External infos : " + listTransactionInfo);
        return listTransactionInfo;
    }
}
